<wsdl:definitions
     name="pollingBoletos"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ITEC.EBS.SoaSuite/BoletoItau/pollingBoletos"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ITEC.EBS.SoaSuite/BoletoItau/pollingBoletos"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:pc="http://xmlns.oracle.com/pcbpel/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/pollingBoletos"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="pollingBoletos_plt" >
    <plt:role name="pollingBoletos_role" >
      <plt:portType name="tns:pollingBoletos_ptt" />
    </plt:role>
  </plt:partnerLinkType>
  <plt:partnerLinkType name="pollingBoletos_plt" >
    <plt:role name="pollingBoletos_role" >
      <plt:portType name="tns:pollingBoletos_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/pollingBoletos" schemaLocation="../Schemas/pollingBoletos_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="TktArBoletoRemessaCollection_msg">
        <wsdl:part name="TktArBoletoRemessaCollection" element="top:TktArBoletoRemessaCollection"/>
    </wsdl:message>
    <wsdl:portType name="pollingBoletos_ptt">
        <wsdl:operation name="receive">
            <wsdl:input message="tns:TktArBoletoRemessaCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
